config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :admins, {
  sessions: 'admin/sessions',
  registrations: '/admins/sign_up',
  passwords: 'admin/passwords'
}

  root to: 'employees#index'
  resources :employees do
    resources :documents, only: [:create, :show, :destroy]
    post 'employee_documents' => 'documents#create', as: :employee_documents # ファイルのアップロード用のルートを追加
    collection do
      delete :batch_delete
    end
  end

  delete 'delete_document/:id' => 'documents#destroy', as: :delete_document
  
  # WebpackerがビルドしたJavaScriptファイルにアクセスするためのルート
  get '/packs/js/application-468255184b399d3d4617.js', to: redirect('assets/application-468255184b399d3d4617.js')
  get '/assets/application-468255184b399d3d4617.js', to: redirect('/assets/application-468255184b399d3d4617.js')
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
    
    belongs_to :employee
    has_many_attached :files

end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :documents, dependent: :destroy
    

    def full_name
        self.last_name + self.first_name
    end

    def full_name_kana
        self.last_name_kana + self.first_name_kana
    end

    def age
        (Date.today - birthday).to_i / 365
    end
      
    def address_display
        "〒" + postal_code + " " + address
    end

    validates :first_name_kana, :last_name_kana, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
    validates :postal_code, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999 },
                  format: { with: /\A[0-9]+\z/ }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?
    def after_sign_in_path_for(resource)
        root_path
    end

    def after_sign_out_path_for(resource)
        admin_session_path
    end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
    end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
    def show
      @employee = Employee.find(params[:employee_id])
      @document = @employee.documents.find(params[:id])
    end
  
    def create
        @employee = Employee.find(params[:employee_id])
        params[:files].each_with_index do |file, index|
          description = params[:descriptions][index]
          @document = @employee.documents.create(description: description)
          @document.files.attach(file)
        end
        redirect_to employee_path(@employee), notice: "ファイルをアップロードしました"
    end

    def destroy
        @document = Document.find(params[:id])
        @employee = @document.employee
        @document.destroy
        redirect_to employee_path(@employee), notice: "ファイルを削除しました"
    end
      
        
      
  
    private
  
    def document_params
        params.require(:document).permit(:description, files: [])
    end
      
  end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_admin!

  require 'happybirthday'

  def index
    @employee = Employee.new
    @employees = Employee.all
  end
  
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to root_path, notice: "従業員の登録が完了しました"
    else
      flash.now[:alert] = "登録に失敗しました。正しい情報を入力してください。"
      render :new  # 正しいテンプレートを指定する
    end
  end
  

  def show
    @employee = Employee.find(params[:id])
    @address_display = @employee.address_display
    @documents = @employee.documents
    @new_document = Document.new
  end
  
  def batch_delete
    if params[:employee_ids].nil? || params[:employee_ids].empty?
      flash[:alert] = "チェックボックスを選択してください。"
      redirect_to employees_path
    else
    Employee.where(id: params[:employee_ids]).destroy_all
    redirect_to employees_path, notice: '選択した従業員が削除されました。'
  end
end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to @employee, notice: "従業員の情報を更新しました"
    else
      flash.now[:alert] = "登録に失敗しました。正しい情報を入力してください。"
      render :edit
    end
  end
  

  

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
  redirect_to employees_path, notice: "従業員の削除が完了しました"
  end

  
  
  private

  def calculate_age(birthday)
    birthday = Happybirthday.born_on(birthday)
    birthday.age.years_old
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :birthday, :postal_code, :address, :telephone_number, :start_date, :end_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, local: true do |f| %>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.label :last_name,"姓" %>
      <%= f.text_field :last_name, class: "form-control", required: true %>
    </div>
    <div class="col-sm-6">
      <%= f.label :first_name,"名" %>
      <%= f.text_field :first_name, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-6">
      <%= f.label :last_name_kana,"姓カナ" %>
      <%= f.text_field :last_name_kana, class: "form-control", required: true %>
    </div>
    <div class="col-sm-6">
      <%= f.label :first_name_kana,"名カナ" %>
      <%= f.text_field :first_name_kana, class: "form-control", required: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :birthday,"生年月日" %>
    <div class="row col-sm-10">
      <%= f.date_select :birthday,
            { use_month_numbers: true, start_year: (Time.now.year - 60),
            end_year: (Time.now.year), default: nil,
            prompt: { day: '日', month: '月', year: '年'},
            include_blank: false, required: true
            },
            { class: "form-control mx-2", required: true, 
            style: 'display: inline-block;width: auto;'
            }
        %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :postal_code,"郵便番号" %>
    <div class="row">
      <div class="col-3">
        <%= f.text_field :postal_code, class: "form-control form-control-sm w10", required: true %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :address, "住所" %>
    <%= f.text_field :address, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :telephone_number,"電話番号" %>
    <%= f.telephone_field :telephone_number, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :start_date, "入社日" %>
    <div class="row col-sm-10">
      <%= f.date_select :start_date,
        {
            use_month_numbers: true,
            start_year: (Time.now.year - 20),
            end_year: (Time.now.year + 5),
            default: nil,
            prompt: { day: '日', month: '月', year: '年'},
            include_blank: false,
        },
        {
            class: "form-control mx-2", 
            style: 'display: inline-block;width: auto;'
        }
        %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_date, "退社日" %>
    <div class="row col-sm-10">
      <%= f.date_select :end_date,
        {
            use_month_numbers: true,
            start_year: (Time.now.year - 5),
            end_year: (Time.now.year + 5),
            default: nil,
            prompt: { day: '日', month: '月', year: '年'},
            include_blank: false,
        },
        {
            class: "form-control mx-2", 
            style: 'display: inline-block;width: auto;'
        }
        %>
    </div>
  </div>
  <div class="modal-footer mt-3">
    <div class="row">
      <div class='col-xs-6 text-right'>
        <div class='btn-group btn-add-block'>
          <%= f.submit "登録", class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="container">
  <h1>従業員情報編集</h1>
  <div class="row">
    <div class="col-md-6 mb-4">
      <%= render partial: 'form', locals: { employee: @employee } %>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="container d-none d-md-block">
  <div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h1 class="mb-0 text-secondary">従業員一覧</h1>
      <div>
        <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">
          <i class="fa-solid fa-user-plus"></i> 新規登録
        </button>
        <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
    <div class="card-body">
      <%= form_with(url: batch_delete_employees_path, method: :delete) do |f| %>
        <table class="table table-striped table-hover">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">氏名</th>
              <th scope="col">生年月日</th>
              <th scope="col">年齢</th>
              <th scope="col">住所</th>
              <th scope="col">入社日</th>
              <th scope="col">退社日</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <% @employees.each do |employee| %>
              <tr>
                <td><%= check_box_tag 'employee_ids[]', employee.id, false, class: 'form-check-input' %></td>
                <td><%= link_to employee.full_name, employee_path(employee), class: "text-decoration-none fw-bold text-dark" %></td>
                <td><%= employee.birthday %></td>
                <td><%= employee.age %></td>
                <td><%= employee.address %></td>
                <td><%= employee.start_date %></td>
                <td><%= employee.end_date %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= f.submit '一括削除', class: 'btn btn-danger', data: { confirm: "本当に削除しますか？" } %>
      <% end %>
    </div>
  </div>
</div>
<div class="container d-md-none">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="mb-2 text-secondary">従業員一覧</h1>
    <div>
      <button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo">
        <i class="fa-solid fa-user-plus"></i> 新規登録
      </button>
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-danger btn-sm" %>
    </div>
  </div>
  <% @employees.each do |employee| %>
    <%# スマホでのアコーディオン表示 %>
    <div class="accordion" id="employeeAccordion">
      <div class="accordion-item">
        <h2 class="accordion-header">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse_employee_<%= employee.id %>" aria-expanded="false" aria-controls="collapse_employee_<%= employee.id %>">
            <%= employee.full_name %>
          </button>
        </h2>
        <div id="collapse_employee_<%= employee.id %>" class="accordion-collapse collapse" aria-labelledby="heading_employee_<%= employee.id %>" data-bs-parent="#employeeAccordion">
          <div class="accordion-body">
            <p>生年月日: <%= employee.birthday %></p>
            <p>年齢: <%= employee.age %></p>
            <p>住所: <%= employee.address %></p>
            <p>入社日: <%= employee.start_date %></p>
            <p>退社日: <%= employee.end_date %></p>
            <%= link_to "詳細", employee_path(employee), class: "btn btn-primary btn-sm" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!-- モーダル -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規登録</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%# editとのパーシャル %>
        <%= render partial: 'form', locals: { employee: @employee } %>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<%= render 'form' %>

app/views/employees/show.html.erb
<div class="container">
  <h1 class="mb-2 text-secondary">従業員詳細</h1>
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= link_to '従業員一覧に戻る', root_path, class: "btn btn-secondary mb-3" %>
  </div>
  <div class="row">
    <div class="col-md-6 mb-3">
      <div class="card">
        <div class="card-body">
          <table class="table table-bordered table-striped">
            <tr>
              <th class="w-25">氏名</th>
              <td><%= @employee.full_name %></td>
            </tr>
            <tr>
              <th>フリガナ</th>
              <td><%= @employee.full_name_kana %></td>
            </tr>
            <tr>
              <th>生年月日</th>
              <td><%= @employee.birthday %></td>
            </tr>
            <tr>
              <th>年齢</th>
              <td><%= @employee.age %></td>
            </tr>
            <tr>
              <th>住所</th>
              <td><%= @address_display %></td>
            </tr>
            <tr>
              <th>電話番号</th>
              <td><%= @employee.telephone_number %></td>
            </tr>
            <tr>
              <th>入社日</th>
              <td><%= @employee.start_date %></td>
            </tr>
            <tr>
              <th>退社日</th>
              <td><%= @employee.end_date %></td>
            </tr>
          </table>
          <%= link_to "編集する", edit_employee_path, class: "btn btn-outline-info" %>
          <%= link_to "削除", employee_path(@employee), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger btn-sm" %>
        </div>
      </div>
    </div>
    <div class="col-md-6 mb-4">
      <div class="card">
        <div class="card-body">
          <%= form_with(url: employee_documents_path(@employee), multipart: true) do |f| %>
            <div class="form-group">
              <%= f.file_field :files, multiple: true, class: "form-control form-control-sm", onchange: "addFileField(this)" %>
            </div>
            <div id="file_fields" class="form-group"></div>
            <%= f.submit "アップロード", class: "btn btn-primary btn-block mt-2", style: "display: none;" %>
          <% end %>
          <% if @employee.documents.any? %>
            <div class="mt-4">
              <h2>アップロードされたファイル</h2>
              <ul class="list-unstyled">
                <% @employee.documents.each do |document| %>
                  <li>
                    <strong><%= document.description %>:</strong>
                    <% if document.files.attached? %>
                      <i class="fa-regular fa-file"></i> <%= link_to document.files.map(&:filename).join(', '), rails_blob_path(document.files.first), class: "text-decoration-none link-secondary" %>
                      <%= link_to "", delete_document_path(document.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "text-decoration-none link-danger fa-regular fa-trash-can" %>
                    <% else %>
                      <span>ファイルがありません</span>
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function addFileField(input) {
    var files = input.files;
    var fileFields = document.getElementById('file_fields');
    var uploadButton = document.querySelector('[type="submit"]');

    fileFields.innerHTML = '';

    for (var i = 0; i < files.length; i++) {
      var fileField = document.createElement('div');
      fileField.className = 'file_field';
      fileField.innerHTML = `
        <input type="text" name="descriptions[]" placeholder="ファイル説明" class="form-control form-control-sm mt-3">
        <input type="file" name="files[]" value="${files[i].name}" style="display: none;">
        <span>${files[i].name}</span>`;
      fileFields.appendChild(fileField);
    }
    uploadButton.style.display = files.length > 0 ? 'block' : 'none'; // ファイルが選択されたらアップロードボタンを表示
  }

  function removeFileField(element) {
    element.parentNode.remove();
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/application.css">
    <meta name="turbolinks-visit-control" content="reload">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/3e48c8f6cb.js" crossorigin="anonymous"></script>
    <title>EmployeeSys</title>
  </head>
  <body>
    <p class="notice text-success mt-2 p-2"><%= notice %></p>
    <p class="alert text-danger mt-2 p-2"><%= alert %></p>
    <%= yield %>
  </body>
</html>